### PR TITLE
Add BINLOG_ADAPT_CONCEPT

### LINKED ISSUE #150: Log concepts
Is it possible for binlog to support adapting a C++20 concept to avoid having the base type being adapted by the user?

### PR DESCRIPTION
**Pull request by erenon**
- Add BINLOG_ADAPT_CONCEPT
- Build using C++20 in CI instead of C++17

Fixes #150 . @andrewkcorcoran please take a look.

### CODE REVIEW

**Comment by erenon** [comment]
CI fails because of toolchain issue / CMake fails to detect that LTO will not work. (see #136) Finally there's a repro - so I can fix that as well : )

**Comment by erenon** [comment]
Also fixes #136

**Comment by andrewkcorcoran** [comment]
Looks good. Templated concepts might also be an interesting challenge.

**Comment by erenon** [comment]
@spektrof ptal and merge. Thanks!

**Review by spektrof — APPROVED** [review]

**Comment by erenon** [comment]
> Looks good. Templated concepts might also be an interesting challenge.

If you have a use-case, please file a ticket with an example that shows "exactly" what you are looking for - and I'll get there eventually : ) thanks.

**Pull request merged**
